/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DaftarOnlineRouteImport } from './routes/daftar-online'
import { Route as DokterRouteImport } from './routes/dokter'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DashboardpanelIndexRouteImport } from './routes/dashboardpanel/index'
import { Route as DashboardpanelBlogRouteImport } from './routes/dashboardpanel/blog'
import { Route as DashboardpanelDokterRouteImport } from './routes/dashboardpanel/dokter'
import { Route as DashboardpanelLayananRouteImport } from './routes/dashboardpanel/layanan'
import { Route as DashboardpanelLoginRouteImport } from './routes/dashboardpanel/login'
import { Route as DashboardpanelPendaftaranRouteImport } from './routes/dashboardpanel/pendaftaran'
import { Route as DashboardpanelTestimonialRouteImport } from './routes/dashboardpanel/testimonial'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DaftarOnlineRoute = DaftarOnlineRouteImport.update({
  id: '/daftar-online',
  path: '/daftar-online',
  getParentRoute: () => rootRouteImport,
} as any)
const DokterRoute = DokterRouteImport.update({
  id: '/dokter',
  path: '/dokter',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardpanelIndexRoute = DashboardpanelIndexRouteImport.update({
  id: '/dashboardpanel/',
  path: '/dashboardpanel/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardpanelBlogRoute = DashboardpanelBlogRouteImport.update({
  id: '/dashboardpanel/blog',
  path: '/dashboardpanel/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardpanelDokterRoute = DashboardpanelDokterRouteImport.update({
  id: '/dashboardpanel/dokter',
  path: '/dashboardpanel/dokter',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardpanelLayananRoute = DashboardpanelLayananRouteImport.update({
  id: '/dashboardpanel/layanan',
  path: '/dashboardpanel/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardpanelLoginRoute = DashboardpanelLoginRouteImport.update({
  id: '/dashboardpanel/login',
  path: '/dashboardpanel/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardpanelPendaftaranRoute =
  DashboardpanelPendaftaranRouteImport.update({
    id: '/dashboardpanel/pendaftaran',
    path: '/dashboardpanel/pendaftaran',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardpanelTestimonialRoute =
  DashboardpanelTestimonialRouteImport.update({
    id: '/dashboardpanel/testimonial',
    path: '/dashboardpanel/testimonial',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/daftar-online': typeof DaftarOnlineRoute
  '/dokter': typeof DokterRoute
  '/layanan': typeof LayananRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboardpanel/blog': typeof DashboardpanelBlogRoute
  '/dashboardpanel/dokter': typeof DashboardpanelDokterRoute
  '/dashboardpanel/layanan': typeof DashboardpanelLayananRoute
  '/dashboardpanel/login': typeof DashboardpanelLoginRoute
  '/dashboardpanel/pendaftaran': typeof DashboardpanelPendaftaranRoute
  '/dashboardpanel/testimonial': typeof DashboardpanelTestimonialRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboardpanel/': typeof DashboardpanelIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/daftar-online': typeof DaftarOnlineRoute
  '/dokter': typeof DokterRoute
  '/layanan': typeof LayananRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboardpanel/blog': typeof DashboardpanelBlogRoute
  '/dashboardpanel/dokter': typeof DashboardpanelDokterRoute
  '/dashboardpanel/layanan': typeof DashboardpanelLayananRoute
  '/dashboardpanel/login': typeof DashboardpanelLoginRoute
  '/dashboardpanel/pendaftaran': typeof DashboardpanelPendaftaranRoute
  '/dashboardpanel/testimonial': typeof DashboardpanelTestimonialRoute
  '/blog': typeof BlogIndexRoute
  '/dashboardpanel': typeof DashboardpanelIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/daftar-online': typeof DaftarOnlineRoute
  '/dokter': typeof DokterRoute
  '/layanan': typeof LayananRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboardpanel/blog': typeof DashboardpanelBlogRoute
  '/dashboardpanel/dokter': typeof DashboardpanelDokterRoute
  '/dashboardpanel/layanan': typeof DashboardpanelLayananRoute
  '/dashboardpanel/login': typeof DashboardpanelLoginRoute
  '/dashboardpanel/pendaftaran': typeof DashboardpanelPendaftaranRoute
  '/dashboardpanel/testimonial': typeof DashboardpanelTestimonialRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboardpanel/': typeof DashboardpanelIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/daftar-online'
    | '/dokter'
    | '/layanan'
    | '/blog/$slug'
    | '/dashboardpanel/blog'
    | '/dashboardpanel/dokter'
    | '/dashboardpanel/layanan'
    | '/dashboardpanel/login'
    | '/dashboardpanel/pendaftaran'
    | '/dashboardpanel/testimonial'
    | '/blog/'
    | '/dashboardpanel/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/daftar-online'
    | '/dokter'
    | '/layanan'
    | '/blog/$slug'
    | '/dashboardpanel/blog'
    | '/dashboardpanel/dokter'
    | '/dashboardpanel/layanan'
    | '/dashboardpanel/login'
    | '/dashboardpanel/pendaftaran'
    | '/dashboardpanel/testimonial'
    | '/blog'
    | '/dashboardpanel'
  id:
    | '__root__'
    | '/'
    | '/daftar-online'
    | '/dokter'
    | '/layanan'
    | '/blog/$slug'
    | '/dashboardpanel/blog'
    | '/dashboardpanel/dokter'
    | '/dashboardpanel/layanan'
    | '/dashboardpanel/login'
    | '/dashboardpanel/pendaftaran'
    | '/dashboardpanel/testimonial'
    | '/blog/'
    | '/dashboardpanel/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DaftarOnlineRoute: typeof DaftarOnlineRoute
  DokterRoute: typeof DokterRoute
  LayananRoute: typeof LayananRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DashboardpanelBlogRoute: typeof DashboardpanelBlogRoute
  DashboardpanelDokterRoute: typeof DashboardpanelDokterRoute
  DashboardpanelLayananRoute: typeof DashboardpanelLayananRoute
  DashboardpanelLoginRoute: typeof DashboardpanelLoginRoute
  DashboardpanelPendaftaranRoute: typeof DashboardpanelPendaftaranRoute
  DashboardpanelTestimonialRoute: typeof DashboardpanelTestimonialRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DashboardpanelIndexRoute: typeof DashboardpanelIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daftar-online': {
      id: '/daftar-online'
      path: '/daftar-online'
      fullPath: '/daftar-online'
      preLoaderRoute: typeof DaftarOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokter': {
      id: '/dokter'
      path: '/dokter'
      fullPath: '/dokter'
      preLoaderRoute: typeof DokterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboardpanel/': {
      id: '/dashboardpanel/'
      path: '/dashboardpanel'
      fullPath: '/dashboardpanel/'
      preLoaderRoute: typeof DashboardpanelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboardpanel/blog': {
      id: '/dashboardpanel/blog'
      path: '/dashboardpanel/blog'
      fullPath: '/dashboardpanel/blog'
      preLoaderRoute: typeof DashboardpanelBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboardpanel/dokter': {
      id: '/dashboardpanel/dokter'
      path: '/dashboardpanel/dokter'
      fullPath: '/dashboardpanel/dokter'
      preLoaderRoute: typeof DashboardpanelDokterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboardpanel/layanan': {
      id: '/dashboardpanel/layanan'
      path: '/dashboardpanel/layanan'
      fullPath: '/dashboardpanel/layanan'
      preLoaderRoute: typeof DashboardpanelLayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboardpanel/login': {
      id: '/dashboardpanel/login'
      path: '/dashboardpanel/login'
      fullPath: '/dashboardpanel/login'
      preLoaderRoute: typeof DashboardpanelLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboardpanel/pendaftaran': {
      id: '/dashboardpanel/pendaftaran'
      path: '/dashboardpanel/pendaftaran'
      fullPath: '/dashboardpanel/pendaftaran'
      preLoaderRoute: typeof DashboardpanelPendaftaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboardpanel/testimonial': {
      id: '/dashboardpanel/testimonial'
      path: '/dashboardpanel/testimonial'
      fullPath: '/dashboardpanel/testimonial'
      preLoaderRoute: typeof DashboardpanelTestimonialRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DaftarOnlineRoute: DaftarOnlineRoute,
  DokterRoute: DokterRoute,
  LayananRoute: LayananRoute,
  BlogSlugRoute: BlogSlugRoute,
  DashboardpanelBlogRoute: DashboardpanelBlogRoute,
  DashboardpanelDokterRoute: DashboardpanelDokterRoute,
  DashboardpanelLayananRoute: DashboardpanelLayananRoute,
  DashboardpanelLoginRoute: DashboardpanelLoginRoute,
  DashboardpanelPendaftaranRoute: DashboardpanelPendaftaranRoute,
  DashboardpanelTestimonialRoute: DashboardpanelTestimonialRoute,
  BlogIndexRoute: BlogIndexRoute,
  DashboardpanelIndexRoute: DashboardpanelIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
